//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.DA.AvdService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Advertising", Namespace="http://schemas.datacontract.org/2004/07/AdvertisingService.Dto")]
    [System.SerializableAttribute()]
    public partial class Advertising : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extensions {
            get {
                return this.ExtensionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionsField, value) != true)) {
                    this.ExtensionsField = value;
                    this.RaisePropertyChanged("Extensions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageData {
            get {
                return this.ImageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDataField, value) != true)) {
                    this.ImageDataField = value;
                    this.RaisePropertyChanged("ImageData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AvdService.IAdvertisingProvider")]
    public interface IAdvertisingProvider {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvertisingProvider/GetAdvertising", ReplyAction="http://tempuri.org/IAdvertisingProvider/GetAdvertisingResponse")]
        EC.DA.AvdService.Advertising[] GetAdvertising(int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvertisingProvider/GetAdvertising", ReplyAction="http://tempuri.org/IAdvertisingProvider/GetAdvertisingResponse")]
        System.Threading.Tasks.Task<EC.DA.AvdService.Advertising[]> GetAdvertisingAsync(int quantity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdvertisingProviderChannel : EC.DA.AvdService.IAdvertisingProvider, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdvertisingProviderClient : System.ServiceModel.ClientBase<EC.DA.AvdService.IAdvertisingProvider>, EC.DA.AvdService.IAdvertisingProvider {
        
        public AdvertisingProviderClient() {
        }
        
        public AdvertisingProviderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdvertisingProviderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvertisingProviderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvertisingProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EC.DA.AvdService.Advertising[] GetAdvertising(int quantity) {
            return base.Channel.GetAdvertising(quantity);
        }
        
        public System.Threading.Tasks.Task<EC.DA.AvdService.Advertising[]> GetAdvertisingAsync(int quantity) {
            return base.Channel.GetAdvertisingAsync(quantity);
        }
    }
}
