USE [master]
GO

/****** Object:  Database [EC.DB]    Script Date: 27.05.2018 17:36:15 ******/
CREATE DATABASE [EC.DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N' EC.DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ EC.DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N' EC.DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ EC.DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [EC.DB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EC.DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EC.DB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EC.DB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EC.DB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EC.DB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EC.DB] SET ARITHABORT OFF 
GO

ALTER DATABASE [EC.DB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EC.DB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EC.DB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EC.DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EC.DB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EC.DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EC.DB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EC.DB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EC.DB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EC.DB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EC.DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EC.DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EC.DB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EC.DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EC.DB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EC.DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EC.DB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EC.DB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EC.DB] SET  MULTI_USER 
GO

ALTER DATABASE [EC.DB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EC.DB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EC.DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EC.DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EC.DB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EC.DB] SET QUERY_STORE = OFF
GO

USE [EC.DB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [EC.DB] SET  READ_WRITE 
GO